public with sharing class CreatingTestingData {
	public static void createTestData(){
		DoctorManaging.addDoctor(1, 'Michal','Adamczyk','Title','09985','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Polska','Kielce','Krakowska',34,55,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(2, 'Karol','Lipiec','Title','10089','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Francja','Paris','Krakowska',10,4,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(3, 'Anna','Toporek','Title','66678','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Niemcy','Berlin','Krakowska',2,3,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(4, 'Pawel','Ludwinek','Title','22256','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Polska','Kielce','Krakowska',3,18,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(5, 'Pawel','Adamiec','Title','00085','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Czechy','Praga','Krakowska',4,78,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(6, 'Julia','Wieniawa','Title','10085','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Niemcy','Berlin','Krakowska',1,666,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(7, 'Michal','Izdebski','Title','34985','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Hiszpania','Madryt','Krakowska',2,1,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(8, 'Michal','Jacykow','Title','09100','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Polska','Kielce','Krakowska',38,11,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(9, 'Magdalena','Litwin','Title','19985','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Niemcy','Berlin','Krakowska',100,8,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(10, 'Dorota','Lis','Title','44445','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Belgia','Bruksela','Krakowska',161,161,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		
		DoctorManaging.addDoctor(11, 'Agata','Adamczyk','Title','39985','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Polska','Kielce','Krakowska',4,3,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(12, 'Marta','Kot','Title','79985','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Irlandia','Dublin','Krakowska',120,55,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(13, 'Pawel','Nowak','Title','56985','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Irlandia','Dublin','Krakowska',4,1,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(14, 'Michal','Kowalski','Title','12345','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Polska','Kielce','Krakowska',5,5,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(15, 'Lidia','Trela','Title','87654','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Polska','Kielce','Krakowska',8,16,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(16, 'Adam','Adamczyk','Title','57632','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Niemcy','Berlin','Krakowska',118,2,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(17, 'Marek','Grechuta','Title','17632','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Francja','Paryz','Krakowska',1,10,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(18, 'Stanislaw','Wokulski','Title','88997','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Polska','Kielce','Krakowska',23,334,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(19, 'Izabela','Lecka','Title','00005','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Czechy','Parga','Krakowska',88,8,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(20, 'Karolina','Adamiec','Title','99995','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Hiszpania','Madryt','Krakowska',17,17,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		
		DoctorManaging.addDoctor(21, 'Jan','Nowak','Title','43565','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Polska','Kielce','Krakowska',21,37,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(22, 'Michal','Apacz','Title','03385','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Niemcy','Berlin','Krakowska',1,1,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(23, 'Pawel','Ludwikowski','Title','11183','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Hiszpania','Madryt','Krakowska',8,7,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(24, 'Iwona','Biesaga','Title','09944','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Polska','Kielce','Krakowska',119,1,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(25, 'Michal','Banasik','Title','09176','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Francja','Paryz','Krakowska',55,34,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(26, 'Pawel','Rakoczy','Title','11132','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Francja','Paryz','Krakowska',234,1,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(27, 'Ilona','Polak','Title','01357','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Czechy','Praga','Krakowska',90,10,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(28, 'Pawel','Filipiak','Title','03344','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Polska','Kielce','Krakowska',66,2,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(29, 'Marek','Dziedzic','Title','04455','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Polska','Kielce','Krakowska',88,9,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		DoctorManaging.addDoctor(30, 'Filip','Adamczyk','Title','04433','Position','Department',true,'0-123-456-789','0-987-654-321','email@email.com','Polska','Kielce','Krakowska',111,3,'25-900',true,Date.newInstance(2019,8,30),'Status', true, false);
		
		HospitalManaging.addHospital(1, 'Szpital 1', 'Polska', 'Kielce', 'Warszawska', 3, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(2, 'Szpital 2', 'Niemcy', 'Berlin', 'Warszawska', 10, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(3, 'Szpital 3', 'Francja', 'Paryz', 'Warszawska', 114, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(4, 'Szpital 4', 'Czechy', 'Praga', 'Warszawska', 1, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(5, 'Szpital 5', 'Czechy', 'Praga', 'Warszawska', 16, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(6, 'Szpital 6', 'Polska', 'Kielce', 'Warszawska', 90, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(7, 'Szpital 7', 'Hiszpania', 'Madryt', 'Warszawska', 1, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(8, 'Szpital 8', 'Francja', 'Paryz', 'Warszawska', 88, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(9, 'Szpital 9', 'Niemcy', 'Berlin', 'Warszawska', 666, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(10, 'Szpital 10', 'Czechy', 'Praga', 'Warszawska', 5, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		
		HospitalManaging.addHospital(11, 'Szpital 11', 'Polska', 'Kielce', 'Warszawska', 190, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(12, 'ASzpital 12', 'Polska', 'Kielce', 'Warszawska', 55, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(13, 'Szpital 13', 'Niemcy', 'Berlin', 'Warszawska', 367, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(14, 'ASzpital 14', 'Czechy', 'Praga', 'Warszawska', 311, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(15, 'Szpital 15', 'Hiszpania', 'Madryt', 'Warszawska', 324, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(16, 'ASzpital 16', 'Hiszpania', 'Madryt', 'Warszawska', 567, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(17, 'Szpital 17', 'Francja', 'Paryz', 'Warszawska', 3, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(18, 'Szpital 18', 'Hiszpania', 'Madryt', 'Warszawska', 77, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(19, 'Szpital 19', 'Polska', 'Kielce', 'Warszawska', 78, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		HospitalManaging.addHospital(20, 'Szpital 20', 'Czechy', 'Praga', 'Warszawska', 416, '25-900', '0-999-888-777','0-777-888-999','0-111-222-333','0-333-222-111', 'Mike Vazovsky', 'http://www.ooo.pl', true);
		
		List<Doctor__c> doctors = [select id__c, surname__c, name__c, title__c, licenseNumber__c, position__c, department__c, workPhone__c, privatePhone__c, eMail__c, country__c, street__c, streetNumber__c, houseNumber__c, postalCode__c, isAvailable__c, availableDate__c, status__c, partTime__c, homeConsult__c from Doctor__c where id__c = 2 or id__c = 5 or id__c = 8 or id__c = 11 or id__c = 14 or id__c = 17 or id__c = 20 or id__c = 23 or id__c = 26 or id__c = 29];
		List<Hospital__c> hospitals = [select id__c, name__c, country__c, town__c, street__c, streetNumber__c, postalCode__c, phoneNumber1__c, phoneNumber2__c, faxNumber1__c, faxNumber2__c, chiefOfMedicine__c, salesRep__c, teachingHospital__c from Hospital__c where id__c = 2 or id__c = 4 or id__c = 6 or id__c = 8 or id__c = 10 or id__c = 12 or id__c = 14 or id__c = 16 or id__c = 18 or id__c = 20 or id__c = 22 or id__c = 24 or id__c = 26 or id__c = 28 or id__c = 30];
		for(Integer i=0; i<10; i++){
			Decimal a = i+1;
			HospitalDoctorsManaging.hireDoctorToHospital(a, hospitals[i], doctors[i]);
		}
		
	}
    
}